danger/danger-js

.eslintrc.json
package.json
source/danger.js

Sets up tests

---

.travis.yml
package.json

I think this is what `script` does for node projects, should check

Run danger on this repo 

---

changelog.md
dangerfile.js
package.json
source/ci_source/ci_source.js
source/commands/danger-run.js
source/dsl/git.js
source/platforms/github.js
source/platforms/messaging/violation.js
source/platforms/platform.js
source/runner/Dangerfile.js
source/runner/Executor.js

Still not really doing much testing yet, I'm starting to feel close on having all the structures in place around Danger JS so that I can start writing tests.
This will also remove the fail on non-PR builds.
Hopefully, she should respond about the lack of a changelog entry.

Support commenting on PRs

---

.eslintrc.json
README.md
changelog.md
dangerfile.js
docs/js_glossary.md
source/platforms/github.js
source/platforms/platform.js
source/runner/Executor.js

Update or delete comments

---

README.md
changelog.md
package.json

I'm about to recommend it as being usable in prod.

Update README for Early Adopters

---

README.md
changelog.md
source/ci_source/Fake.js
source/ci_source/ci_source.js

This is a pretty good way to test danger and also a lightweight way to
evaluate if "danger is right for you™". Example in README gives a pretty
good overview.

Allows fakeci to run via DANGER_TEST_PR and DANGER_TEST_REPO env vars

---

changelog.md
source/ci_source/Circle.js
source/ci_source/Fake.js
source/ci_source/Semaphore.js
source/ci_source/Travis.js
source/ci_source/_tests/_semaphore.test.js
source/ci_source/ci_source.js
source/ci_source/ci_source_helpers.js

I need this in order to add danger to metaphysics 👍

Add Semaphore support

---

changelog.md
package.json

Alright, this technique seems to work when I edit the node_modules files 👍

Replace the danger.js.flow with just danger.js that uses the flow annotations

---

README.md
changelog.md
source/ci_source/Fake.js
source/ci_source/_tests/_ci_course.test.js
source/ci_source/ci_source.js

Thanks @dblock for the report, covered by a test now 👍

Adds back the Fake CI option

---

changelog.md
package.json

With all the Jest under the hood changes

Version bump

---

changelog.md
package.json

Prepare for 0.7.2 release

---

changelog.md
package.json

Prepare for release

---

changelog.md
package.json

Looks like I already shipped a 0.7.5

Use 0.8.0 instead

---

README.md

Saw a handful of things in the README that I think we could update. Will comment inline. 🎤

Update README #trivial

---

changelog.md
package.json
yarn.lock

Add jest-environment-node to the package.json

---

changelog.md
dangerfile.js
package.json
source/ambient.d.ts
source/ci_source/providers/_tests/_circle.test.ts
source/commands/danger-local.ts
source/commands/danger-pr.ts
source/commands/danger-run.ts
source/commands/danger.ts
source/platforms/GitHub.ts
source/platforms/github/_tests/pullRequestParser.test.ts
source/platforms/github/pullRequestParser.ts
yarn.lock

Relates to #20 
Allows running your Dangerfile against an arbitrary PR
Will need polish etc, but this is how you can build out a dangerfile without all the crazy env vars we have ATM.

Add support for `danger pr`

---

README.md
changelog.md
package.json
source/dsl/GitDSL.ts
source/dsl/GitHubDSL.ts

* Highlights `danger pr`
* Explains how to do the token dance
* Fixes links for the DSL shapes
* Changes the DSL shape ordering so it's easier to read

Update docs and version bump

---

source/dsl/GitDSL.ts

Simple typo fix, thanks @tivac

[DSL docs] Fix a typo #trivial

---

README.md
changelog.md
package.json
source/ci_source/providers/DockerCloud.ts
source/ci_source/providers/_tests/_dockerCloud.test.ts
yarn.lock

This add support for the [Docker Cloud CI](https://cloud.docker.com)

add support for Docker Cloud CI

---

source/ci_source/providers/index.ts

forgot to add it to the list of providers :man_facepalming:

add dockercloud to list of providers

---

source/ci_source/ci_source.ts
source/ci_source/ci_source_helpers.ts
source/ci_source/providers/Codeship.ts
source/ci_source/providers/index.ts
source/commands/danger-run.ts
source/platforms/github/GitHubAPI.ts

This is an initial implementation

add a codeship provider

---

README.md
changelog.md

Adds a changelog for #142 - and a note on how to parse build logs in Danger

Update CHANGELOG + README

---

source/dsl/DangerResults.ts
source/runner/Dangerfile.ts
source/runner/DangerfileRunner.ts
source/runner/Executor.ts
source/runner/_tests/DangerRunner.test.ts
source/runner/_tests/fixtures/ExampleDangerResults.ts
source/runner/_tests/fixtures/__DangerfileAsync.js
source/runner/_tests/fixtures/__DangerfileCallback.js
source/runner/_tests/fixtures/__DangerfileMultiScheduled.js
source/runner/_tests/fixtures/__DangerfileScheduled.js

This still does not work.
It currently allows functions to be pushed to the scheduled array, and it tries to call them.  I have not had it call successfully yet.
It was pretty late at night when I wrote this, so I apologise if I've missed anything.
Tested with the following dangerfile:
```js
import { warn, scheduled } from 'danger';
const p = new Promise(res => {
setTimeout(() => {
console.log('just finished doing something async');
warn('Async function call');
res();
}, 1000);
});
schedule(async () => {
await p;
});
```
I end up with, at the end, a context that looks like:
```js
{
// ...
warnings: [],
scheduled: [null],
}
```

[WIP] initial implementation to handle async

---

changelog.md
circle.yml
package.json
source/runner/_tests/DangerRunner.test.ts
yarn.lock

Doesn't handle all of the greenskeeper PRs, but it does a bunch and I could manually go through them 👍

Update TypeScript, Jest and the CHANGELOG for async

---

changelog.md
source/dsl/DangerDSL.ts
source/dsl/DangerUtilsDSL.ts
source/runner/DangerUtils.ts
source/runner/Executor.ts
source/runner/_tests/DangerUtils.test.ts

Relates to #80
`danger.utils` includes two functions:
* `href(href: string, text: string): string`
* `sentence(array: Array<string>): string`

Add danger.utils DSL

---

changelog.md
package.json

Prepare for v0.13.0

---

circle.yml

Should stop the disappearing messages.

Switch circle to use the new text-only output

---

dangerfile.ts

I'd like this Dangerfile to be a good example for others to work from, so I've included some more comments throughout and made it flow a bit better.

Clean up, and comment the Dangerfile

---

changelog.md
source/danger.d.ts
source/dsl/GitDSL.ts

Adds a changelog and diff

---

changelog.md
package.json
source/commands/danger-run.ts
source/danger.d.ts
source/dsl/GitHubDSL.ts
source/platforms/GitHub.ts
source/platforms/_tests/_github.test.ts

Builds off #227 and after I started making some examples I noticed a pretty glaring flaw, so I've made it easy to use the API on the current PR.

Adds docs around using the GitHub API

---

docs/guides/culture.html.md
docs/guides/faq.html.md
docs/guides/getting_started.html.md
docs/guides/the_dangerfile.html.md
docs/guides/troubleshooting.html.md
docs/tutorials/dependencies.html.md
docs/tutorials/node-app.html.md
docs/tutorials/node-library.html.md
docs/tutorials/typescript.html.md

More work as I build out Danger.Systems

Improve the docs #trivial

---

docs/guides/getting_started.html.md
docs/guides/the_dangerfile.html.md
source/ci_source/providers/Jenkins.ts

More markdown tweaking. #trivial

---

docs/guides/getting_started.html.md

Fixes a markdown rendering bug on the site.

More docs improvements

---

package.json
source/platforms/github/GitHubUtils.ts
yarn.lock

#trivial
Resolves #255 
There was one new lint violation reported when updating to TSLint 5.3.0. Running `yarn lint -- --fix` locally resolved it. 👍

chore(package): update tslint to version 5.3.0

---

README.md

resolves #117
#trivial
Lemme know if anything else should be included here - based on shipping 0.21.0 earlier this evening. 🙂

docs(readme): document the release process

---

changelog.md
docs/tutorials/node-app.html.md

* need to use github property to access the pr
* the length check does not need a negation

Correct some examples in node-app

---

changelog.md
source/platforms/github/GitHubAPI.ts
source/platforms/github/_tests/_github_api.test.ts

In this case the get /user API is not avaliable
See: https://platform.github.community/t/obtaining-the-id-of-the-bot-user/2076

Support running on a Github App

---

VISION.md

Removes a lot of the "should/might" and replaces with does.

Updates to the VISION file

---

.travis.yml

This commit swaps Node 7 for Node 8 on Travis CI.
#trivial

ci(travis): build on Node 8

---

changelog.md
package.json

OK, everything is looking good.

Prepare for v1.0 🎉

---

.travis.yml
changelog.md
package.json
yarn.lock

Fixes #314 ish, maybe, unsure, but it's all I can do for now.

Update prettier and add slack notifications in travis

---

changelog.md
package.json
yarn.lock

Remove the jest-* deps from Danger

---

docs/guides/troubleshooting.html.md

#trivial
Relates to #326
Grabbed and modified the troubleshooting entry from the [Ruby site](https://gitlab.com/danger-systems/danger.systems/blob/master/static/source/guides/troubleshooting.html.md).

docs(troubleshooting): add CircleCI troubleshooting section

---

changelog.md
dangerfile.ts
source/runner/DangerfileRunner.ts

Bring back the typescript compiler

---

source/runner/_tests/_danger_runner.test.ts

Part of #330 
I thought I skipped these because they weren't working.. Yet, when I went back to take a second look - they worked. Hrm?

Unskips the babel tests

---

changelog.md
scripts/create-danger-dts.ts
scripts/danger-dts.ts
source/danger.d.ts
source/runner/Dangerfile.ts

Update the scheduled types

---

docs/usage/danger-process.md
docs/usage/extending-danger.html.md
source/commands/danger-process.ts
source/commands/danger-run.ts

Improves the docs for danger process 👍

Add some docs for the danger process command

---

changelog.md
source/commands/danger-process.ts
source/commands/utils/reporting.ts

Should make it easier to work with, and actually work as expected.

Improvements to danger process

---

.vscode/extensions.json
changelog.md
source/ci_source/get_ci_source.ts
source/commands/danger-pr.ts
source/commands/danger-process.ts
source/commands/danger-run.ts
source/commands/danger-runner.ts
source/commands/danger.ts
source/commands/utils/getRuntimeCISource.ts
source/commands/utils/repl.ts
source/commands/utils/runDangerSubprocess.ts
source/commands/utils/sharedDangerfileArgs.ts
source/commands/utils/validateDangerfileExists.ts

I'd like to try bring the commands into some form of consolidating, because I'm close to making a decision on #373 - this consolidates some copypasta, and splits out the files a bit into concerns.

Tighten the typings on commands

---

CONTRIBUTING.md
README.md

Related issue https://github.com/danger/danger-js/issues/392

Adds a CONTRIBUTING.md (issue #392)

---

package.json

chore(package): update @types/jest to version 21.1.4

---

changelog.md
docs/tutorials/typescript.html.md
docs/usage/danger-process.html.md
docs/usage/danger-process.md

Updated the docs WRT v2

---

package.json
yarn.lock

Update JSON RFCwhatever dep

---

README.md

It's about time we get some people in there?! :blush:

Add Spectrum badge to README

---

CHANGELOG.md
docs/issue_template.md
package.json
source/ci_source/providers/Circle.ts
source/commands/danger.ts

* Adds an issue template
* Updates the docs for Circle

Takes a stab at packaging up the danger commands for better locked CLI usage

---

CHANGELOG.md
source/commands/utils/runDangerSubprocess.ts

Support passing in the host ENV to the subprocess

---

CHANGELOG.md
source/danger.d.ts
source/dsl/DangerDSL.ts

Fix gloabally typo

---

CHANGELOG.md
source/commands/danger-process.ts
source/commands/danger-run.ts

Small typo fix for a double negative:
> due to ~~not~~ this run not executing

Fix double negative

---

package.json
source/platforms/github/GitHubAPI.ts
source/runner/jsonToDSL.ts
yarn.lock

Update github dep

---

source/commands/init/default-dangerfile.ts

Fix one typo

---

source/danger.d.ts
source/dsl/GitHubDSL.ts

Just updates the reference for the GH node API

Improves API docs - #trivial

---

CHANGELOG.md
source/platforms/github/GitHubAPI.ts

In https://github.com/facebook/react/pull/11865 we chatted so much that Danger wouldn't edit the existing messages. Let's fix this 👍

Paginate all the issues

---

source/ci_source/providers/Nevercode.ts
source/ci_source/providers/_tests/_nevercode.test.ts

Simplifies how Nevercode CISource works by removing async methods & using newly provided Env vars.
- [Env Documentation](https://developer.nevercode.io/v1.0/docs/environment-variables-files)

Nevercode Updated Env Vars

---

README.md

Add Bitrise to the readme

---

.travis.yml
CHANGELOG.md

[Travis] Run jest inline on the danger job

---

CHANGELOG.md
source/danger.d.ts
source/dsl/DangerDSL.ts

Adds Peril typings to the Danger DSL. There's not too much there, but at least I can fix #351

[Peril] Updates the Danger DSL with Peril typings

---

CHANGELOG.md
source/commands/danger-local.ts
source/platforms/LocalGit.ts
source/platforms/git/_tests/local_dangerfile_example.ts

Adds a check for the diff existing on local

---

CONTRIBUTING.md
VISION.md
docs/architecture.md
package.json
source/runner/runners/inline.ts
yarn.lock

Updating docs and adds architecture doc

---

CHANGELOG.md
source/platforms/bitbucket_server/BitBucketServerGit.ts

BitBucket/Stash Server committer

---

CHANGELOG.md
README.md
source/ci_source/providers/TeamCity.ts
source/ci_source/providers/_tests/_teamcity.test.ts
source/ci_source/providers/index.ts

Shamelessly based on the `DockerCloud` provider. 🙂

Add support for TeamCity

---

CHANGELOG.md
source/dsl/DangerResults.ts
source/dsl/_tests/DangerResults.test.ts
source/dsl/_tests/__snapshots__/DangerResults.test.ts.snap
source/platforms/platform.ts
source/runner/Executor.ts

Ensures that Danger JS can make safe assumptions about the data inside the danger results.

Adds support for a validation step on the danger results

---

CHANGELOG.md
package.json
source/danger.d.ts
source/dsl/BitBucketServerDSL.ts
source/platforms/BitBucketServer.ts
source/platforms/bitbucket_server/BitBucketServerAPI.ts
source/platforms/bitbucket_server/BitBucketServerGit.ts
source/platforms/bitbucket_server/_tests/__snapshots__/_bitbucket_server_git.test.ts.snap
source/platforms/bitbucket_server/_tests/_bitbucket_server_api.test.ts
source/platforms/bitbucket_server/_tests/_bitbucket_server_git.test.ts
source/platforms/git/gitJSONToGitDSL.ts
source/runner/Executor.ts
source/runner/templates/_tests/_bitbucketServerTemplate.test.ts
source/runner/templates/bitbucketServerTemplate.ts

Bitbucket Server Inline mode

---

CHANGELOG.md
README.md
source/ci_source/providers/Screwdriver.ts
source/ci_source/providers/_tests/_screwdriver.test.ts
source/ci_source/providers/index.ts

Hi! 👋 
This adds support for [Screwwdriver CI](http://screwdriver.cd). It's an open source, self hosted CI that we use at Yahoo. It's based on the Environment Variables described in https://docs.screwdriver.cd/user-guide/environment-variables

Add support for Screwdriver CI

---

CHANGELOG.md
source/runner/Executor.ts

Fix previousComments error

---

CHANGELOG.md
package.json
yarn.lock

Will ship this to npm  if it's green 👍

Update vm2 to be a published release

---

.travis.yml

Tests with 10, now that we've had the first patch

Add node 10 to tests

---

CHANGELOG.md
dangerfile.ts
package.json
source/api/fetch.ts
source/commands/ci/reset-status.ts
source/commands/ci/runner.ts
source/commands/danger-pr.ts
source/commands/danger-process.ts
source/commands/danger-runner.ts
source/commands/utils/runDangerSubprocess.ts
source/debug.ts
source/platforms/BitBucketServer.ts
source/platforms/bitbucket_server/BitBucketServerAPI.ts
source/platforms/bitbucket_server/BitBucketServerGit.ts
source/platforms/git/localGetCommits.ts
source/platforms/git/localGetDiff.ts
source/platforms/git/localGetFileAtSHA.ts
source/platforms/github/GitHubAPI.ts
source/platforms/github/GitHubGit.ts
source/platforms/github/comms/checks/resultsToCheck.ts
source/platforms/github/comms/checksCommenter.ts
source/platforms/github/comms/issueCommenter.ts
source/runner/Executor.ts
source/runner/jsonToDSL.ts
source/runner/runners/inline.ts
source/runner/runners/utils/transpiler.ts
yarn.lock

Lots of stuff to get Peril running with Checks

Improve peril checks

---

CHANGELOG.md
scripts/danger-dts.ts
source/danger.d.ts

Addresses issues raised in https://github.com/Microsoft/TypeScript/issues/24267. You probably want to view with whitespace diffing disabled.

Use top-level exports in '.d.ts' instead of a module augmentation.

---

CHANGELOG.md
package.json
source/platforms/BitBucketServer.ts
source/platforms/FakePlatform.ts
source/platforms/LocalGit.ts
source/platforms/bitbucket_server/BitBucketServerAPI.ts
source/platforms/github/GitHubAPI.ts
source/runner/danger-dsl-json.ts
tsconfig.json
yarn.lock

Turns on strict mode + TS2.9

---

CHANGELOG.md
package.json
source/platforms/github/GitHubUtils.ts
source/runner/runners/inline.ts

This makes it work more reliably.

Some bug fixes for the iterate on an issue DSL

---

CHANGELOG.md
package.json
source/platforms/github/comms/issueCommenter.ts

Improves error reporting for a status post

---

CHANGELOG.md
source/commands/danger-local.ts
source/platforms/git/_tests/localGetCommits.test.ts
source/platforms/git/localGetCommits.ts
source/platforms/git/localGetDiff.ts

WIP, Branched from https://github.com/danger/danger-js/pull/619

Exec to spawn

---

.travis.yml
CHANGELOG.md
docs/issue_template.md
package.json
source/commands/danger-runner.ts
source/commands/utils/runDangerSubprocess.ts
source/dsl/DangerResults.ts

Been seeing this error occasionally in prod, and it just happened in danger-swift

Improves the error handling on the status report for a commit

---

CHANGELOG.md
source/runner/Executor.ts

This is additional logging to help diagnose https://github.com/ashfurrow/peril-settings/issues/8

Adds more logging to handleResultsPostingToPlatform

---

CHANGELOG.md
source/danger.d.ts
source/dsl/GitHubDSL.ts
source/platforms/github/GitHubUtils.ts

I was going to use this in a few places, figured it made sense to centralize instead.

Adds a create/update label function to the github utils func

---

VISION.md

Fixes typo in VISION.md

---

CHANGELOG.md
package.json
source/commands/utils/runDangerSubprocess.ts
source/runner/Executor.ts

I wasn't seeing logs in https://github.com/artsy/force/pull/3061 - normally I'm always running in verbose mode, so I didn't spot this issue.

Make sure that logs are shwon from inside the runner

---

CHANGELOG.md
source/commands/danger-pr.ts

Fix Danger PR not skipping CI checks

---

CHANGELOG.md
README.md
source/ci_source/providers/Netlify.ts
source/ci_source/providers/_tests/_netlify.test.ts
source/ci_source/providers/index.ts

This PR adds Netlify as a CI provider

Add CI integration for Netlify

---

source/platforms/_tests/fixtures/bbs-dsl-input.json
source/platforms/bitbucket_server/_tests/_bitbucket_server_git.test.ts
source/runner/Executor.ts

Thanks to @azz's solid tests this was pretty trivial  👍 
/cc @f-meloni 
merge on green

Adds a fixture for what the entire DSL JSON looks like for BBS

---

CHANGELOG.md
source/platforms/bitbucket_server/BitBucketServerGit.ts
source/platforms/bitbucket_server/_tests/__snapshots__/_bitbucket_server_git.test.ts.snap

Don't know why, but `baseSHA` and `headSHA` for `BitBucketServer` was wrong.

Fix BitBucket Server GitDSL

---

source/ci_source/providers/GitHubActions.ts

I saw this comment while fixing that other thing. Is this the URL and format that you want to see here?

Link to the documentation for GitHub Actions

---

CHANGELOG.md
source/commands/danger-pr.ts

First PR on Danger-js and first time i write something with js :D

Support danger pr also on BitBucket server

---

CHANGELOG.md
package.json
source/platforms/github/GitHubAPI.ts
source/platforms/github/_tests/_github_git.test.ts
source/platforms/github/_tests/fixturedGitHubDSL.ts
source/runner/jsonToDSL.ts
yarn.lock

Re:  https://github.com/danger/danger-js/issues/812
This does seem to only be a warning though, so I'm not sure if it fixes the issue entirely.

Updates the usage of octokit to remove warnings

---

CHANGELOG.md
source/commands/danger-pr.ts

Lets --json or --js not require a dangerfile

---

source/commands/danger-pr.ts
source/danger.d.ts
source/dsl/GitHubDSL.ts

Extend the DSL a bit, ensure --json doesn't print to stdout and trunc…ate the access token so it doesn't accidentally leak

More typedefs and a bit more --json polish

---

CHANGELOG.md
source/dsl/DangerResults.ts
source/dsl/_tests/__snapshots__/DangerResults.test.ts.snap
source/dsl/_tests/fixtures/ExampleDangerResults.ts
source/runner/Executor.ts

I've got the changes of the other PR here too by mistake :(, but they are just 2 lines

Fix meta on prs

---

CHANGELOG.md
source/danger.d.ts

add docs to GitHubMergeRef

---

CHANGELOG.md
docs/architecture.md
docs/usage/danger-process.html.md

Fix typo.
And docs were formatted by prettier automatically.

docs: fix typo

---

CHANGELOG.md
README.md
source/ci_source/providers/CodeBuild.ts
source/ci_source/providers/_tests/_codebuild.test.ts
source/ci_source/providers/index.ts

Adds support for CodeBuild as a CI source.
I have tested this out in a CodeBuild project already with success 👍 
This closes #843 .

add codebuild to ci source providers

---

CHANGELOG.md
source/commands/ci/_tests/runner.test.ts
source/commands/ci/runner.ts
source/commands/danger-process.ts
source/commands/utils/sharedDangerfileArgs.ts
source/runner/Executor.ts
source/runner/_tests/_executor.test.ts

Is a big change for javascript skills and experience :D
Hope didn't do anything bad :P

Add a strict option to fail the build if there are error on the danger report

---

CHANGELOG.md
source/platforms/github/GitHubAPI.ts
source/runner/_tests/_executor.test.ts
source/runner/templates/githubIssueTemplate.ts

hopefullyy Peril will be using the API correctly now

Improve the commit summaries, and remove unique code

---

.travis.yml
CHANGELOG.md
scripts/danger-dts.ts
source/commands/ci/runner.ts
source/commands/danger-process.ts
source/danger.d.ts
source/dsl/GitDSL.ts

Fixes latest two issues

---

CHANGELOG.md
package.json
scripts/danger-dts.ts
source/commands/utils/chainsmoker.ts
source/danger.d.ts
yarn.lock

The export for chainsmoker was being added on the website incorrectly

Cleans up the declartions and runs prettier over them in memory

---

CHANGELOG.md
README.md
source/ci_source/providers/Codefresh.ts
source/ci_source/providers/_tests/_codefresh.test.ts
source/ci_source/providers/index.ts

Adds support for [Codefresh CI](https://codefresh.io).

Add support for Codefresh CI

---

CHANGELOG.md
source/ci_source/_tests/_get_ci_source.test.ts
source/dsl/BitBucketServerDSL.ts
source/platforms/BitBucketServer.ts
source/platforms/bitbucket_cloud/_tests_/_bitbucket_cloud_git.test.ts
source/platforms/bitbucket_server/BitBucketServerGit.ts
source/platforms/bitbucket_server/_tests/_bitbucket_server_git.test.ts
source/platforms/github/_tests/_github_git.test.ts
source/runner/_tests/jsonToDSL.test.ts
source/runner/jsonToDSL.ts

Expose BitBucketServerAPI

---

CHANGELOG.md

Fix invalid JSON in Changelog

---

CHANGELOG.md
scripts/create-danger-dts.ts
scripts/danger-dts.ts
source/danger.d.ts
source/dsl/Aliases.ts
source/dsl/BitBucketCloudDSL.ts
source/dsl/BitBucketServerDSL.ts
source/dsl/DangerResults.ts
source/dsl/GitDSL.ts
source/dsl/GitHubDSL.ts
source/dsl/GitLabDSL.ts
source/dsl/Violation.ts
source/platforms/bitbucket_server/BitBucketServerAPI.ts
source/platforms/bitbucket_server/BitBucketServerGit.ts

Figured changing the public API wasn't well documented enough, so I gave that a run-through and fixed up the DTS for TS users.
/cc @NMinhNguyen

Adds some improvements to knowing if you've accidentally broken the d eclarations file generation

---

source/ci_source/_tests/ci_source_helper.test.ts
source/ci_source/ci_source_helpers.ts

* add unit test cases
* remove useless legacy comments

Better and clearer helper implementation

---

docs/architecture.md

When i read the source code of project. I find sone useful link for developer is not displayed. I think it will be helpful for more developers if it's displayed.

Fix the break link and make some useful links displyed.

---

source/commands/ci/runner.ts

info when not supported platform is added.

Add gitlab, bitbucket cloud platform to hint

---

CHANGELOG.md
source/ci_source/providers/GitHubActions.ts

Reference: https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswithargs

Improve docs for GitHub Actions

---

CHANGELOG.md
docs/usage/bitbucket_server.html.md
source/platforms/bitbucket_server/BitBucketServerAPI.ts
source/platforms/bitbucket_server/_tests/_bitbucket_server_api.test.ts

feat: added flag to bypass jira/issues check, 🤖🦍🐙

---

CHANGELOG.md
README.md
package.json
source/ci_source/providers/BuddyWorks.ts
source/ci_source/providers/_tests/_buddyWorks.test.ts
source/ci_source/providers/index.ts

Hey 👋 
We'd really like to use DangerJS at @kinsta, so I created a PR to add support for our CI, [buddy.works](https://buddy.works/).
Please let me know if I left something out!
Cheers! 🍻

[Feature]: Add Buddy.works pipeline support

---

source/platforms/github/comms/checks/githubAppSupport.ts

- fixes danger/danger-js#930
- add support for GHE in github checks integration

Bugfix: #930

---

source/.github/workflows/uploadDockerImage.yml

fixes https://github.com/danger/danger-js/issues/923
/cc @SimenB
Will need to wait for a new tag to verify it's all hooked up right though.

Add a docker image

---

CHANGELOG.md
source/ci_source/providers/GitHubActions.ts
source/ci_source/providers/_tests/_gitHubActions.test.ts
source/platforms/github/GitHubAPI.ts

Unfortunately after trying the yesterday PR I found some issues with the previous code.
The good news is that after this change I've tested it and works perfectly also with issue triggers

Fix github actions check

---

source/commands/ci/runner.ts
source/commands/danger-ci.ts
source/runner/Executor.ts
source/runner/_tests/_executor.test.ts

PR for #959
I tested locally in my environment, works just fine, did I forget something?

Add option to not publish checks in danger ci

---

docs/usage/gitlab.html.md
source/ci_source/providers/GitLabCI.ts

- Fixed some Bitbucket references in Gitlab doc
- Added commitHash() onto Gitlab CI platform

Improved gitlab documentation

---

docs/architecture.md

fix architecture doc issues

---

CHANGELOG.md
source/platforms/platform.ts

Don't warn if github token is available in non action format

---

.github/workflows/CI.yml
.travis.yml

This might stop the random reds

Remove the travis integration tests and move those to GH actions

---

.github/ISSUE_TEMPLATE/bug_report.md

We should add a new template for bug reports. This will help others when they want to report a bug.

added a new Bug issue template

---

VISION.md

Part of https://github.com/danger/danger-js/pull/1023

vision.md: fix grammer

---

CHANGELOG.md
README.md

The word teams mean `many teams`. We should use `team's` instead.

fix grammar in README.md

---

CHANGELOG.md
source/platforms/git/localGetCommits.ts

Wait for close event on spawned process in local git

---

CHANGELOG.md
docs/tutorials/transpilation.html.md

Adds documentation on how to disable transpilation.

Document how to disable transpilation

---

package.json
source/ci_source/providers/Bamboo.ts
source/ci_source/providers/_tests/_bamboo.test.ts

Update Bamboo CI source for compatibility with 7.0 version

---

source/platforms/gitlab/GitLabGit.ts

defense code for lower gitlab version

---

CHANGELOG.md
source/dsl/GitDSL.ts
source/platforms/FakePlatform.ts
source/platforms/bitbucket_cloud/_tests_/_bitbucket_cloud_git.test.ts
source/platforms/bitbucket_server/_tests/_bitbucket_server_git.test.ts
source/platforms/git/gitJSONToGitDSL.ts
source/platforms/github/_tests/_github_git.test.ts

add danger.git.head and danger.git.base

---

CHANGELOG.md
source/platforms/pullRequestParser.ts

Fixes #1121 
https://docs.atlassian.com/bitbucket-server/rest/5.16.0/bitbucket-rest.html#personal-repositories

Support Bitbucket Server personal repositories

---

source/platforms/GitLab.ts

Remove debug

---

docs/usage/gitlab.html.md
source/commands/danger-pr.ts
source/platforms/gitlab/GitLabAPI.ts
source/platforms/platform.ts
source/runner/jsonToDSL.ts

At my current project we don't have GitLab access token at CI, but instead we have oauth token. So I added a support of OAuth token usage for GitLab

Add ability to use GitlabApi by oauth token

---

CHANGELOG.md
source/platforms/GitHub.ts

Ensures the PR always has a body

---

docs/tutorials/dependencies.html.md
docs/tutorials/node-library.html.md

I don't remember where I took the new code, probably `index.d.ts`.
This is published here, right?
- https://danger.systems/js/tutorials/dependencies.html

Docs: Update dependencies tutorial to use fileMatch

---

source/danger-incoming-process-schema.json
source/danger-outgoing-process-schema.json

See discussion at:
- https://github.com/danger/danger-js/commit/7fbbbd85a1161d2cebea464d2fbe5032d4610fe3#commitcomment-69339896
Restored with:
```
git show 10.6.4 source/*.json|patch -R -p1
git commit -am 'Restore truncated schema.json from 10.6.4 release commit'
```
cc @orta

Restore truncated schema.json from 10.6.4 release commit

---

source/ci_source/ci_source_helpers.ts
source/dsl/BitBucketCloudDSL.ts
source/dsl/BitBucketServerDSL.ts
source/dsl/GitLabDSL.ts
source/dsl/RepoMetaData.ts
source/platforms/_tests/_bitbucket_cloud.test.ts
source/platforms/_tests/_bitbucket_server.test.ts
source/platforms/_tests/_github.test.ts
source/platforms/bitbucket_cloud/BitBucketCloudAPI.ts
source/platforms/bitbucket_server/BitBucketServerAPI.ts
source/platforms/bitbucket_server/BitBucketServerGit.ts
source/platforms/github/GitHubAPI.ts
source/platforms/gitlab/GitLabAPI.ts

Resolve TODO:
```ts
// TODO: extract out from BitBucket specifically, or create our own type
```

Refactor: Extract RepoMetaData to own file

---

CHANGELOG.md

@ivankatliarchuk entries were duplicates and not sorted.

Fix duplicate users in changelog

---

VISION.md

Fix broken links in VISION.md

---

.github/workflows/publish_package.yml

Revert "add build and push to ghcr similar to danger"

---

.github/workflows/publish_package.yml

Reverts danger/danger-js#1389 - ha, guess I was wrong!

Revert "Revert "add build and push to ghcr similar to danger""

---

source/runner/templates/githubIssueTemplate.ts

Original issue: 
https://github.com/danger/danger-js/issues/1400

Replace deprecated substr with substring in github issue template

---

source/ci_source/providers/GitHubActions.ts

https://github.com/danger/danger-js/issues/1454

chore: update not PR condition for GH workflow

---

CHANGELOG.md
source/danger.ts

Trivial error/docs update, see #1467

[Docs] Clean up dead discussion link - Fixes #1467
